- hosts: localhost
#  vars_files: 
#   - /home/ansible/.confid/confidential
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Create a github Repo
      github_repo:
        github_auth_key: "{{github_token}}"
        username: "{{github_username}}"
        name: "{{github_repo_name}}"
        description: "Create Github repo with Ansible custom module"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      register: result   
      tags:
        - create_repo

    - name: Delete GitHub Repo
      github_repo:
        github_auth_key:  "{{github_token}}" 
        username: "{{github_username}}"
        name: "{{github_repo_name}}"
        state: absent 
      tags:
        - delete_repo
